# Generated by Django 6.0.4 on 2026-05-13 23:01

import ckeditor.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='precio',
        ),
        migrations.AddField(
            model_name='auto',
            name='descripcion',
            field=ckeditor.fields.RichTextField(default='Sin descripcion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auto',
            name='fecha_publicacion',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='autos'),
        ),
    ]
